before_script: cd Application/easyapply
language: java
jdk: oraclejdk11

script:
- ./mvnw clean install -Dmaven.javadoc.skip=true -B -V
-  cd ../../Extension/; npm install --save-dev git-format-staged husky; cd ../frontend/easyapply/; npm install --save-dev git-format-staged husky; cd ../Application/easyapply;

after_success:
  - bash <(curl -s https://codecov.io/bash)
